# General.
title: "Sex and Drugs and Guns and Code"
subtitle:
- "What you need to know about politics, economics, justice, and power"
- "to be successful in the tech industry today."
year: 2020
email: "gvwilson@third-bit.com"
domain: "https://gvwilson.github.io/sdgc/"
repo: "https://github.com/gvwilson/sdgc/"

# Jekyll settings.
repository: <USERNAME>/<PROJECT>
defaults:
- scope:
    path: ""
  values:
    layout: "page"
kramdown:
  toc_levels: "2"
exclude:
- "*/bin"
- "Makefile"
- "README.md"
- "bin"
- "etc"
